Add an example application how to use Request Logger middleware
simplybusiness/twiglet-ruby pull request #3
Opened 2020-07-10 11:33 UTC by punitcse

# What

Add an example application how to use Request Logger.

# Why

So people can copy the example request logger.

@simplybusiness/silversmiths

2020-07-10 12:12 UTC, sleepyfox reviewed
:ship:

2020-07-10 16:03 UTC, rifkinni requested changes

2020-07-10 16:03 UTC, rifkinni commented on example_rack_app.rb
> +class RequestLogger
Can we add the tests for this too?

2020-07-13 15:07 UTC, rifkinni approved these changes
🦄

2020-07-13 15:09 UTC, merged